"""Add registration_requests table

Revision ID: 7ada63c51881
Revises: 
Create Date: 2025-05-06 01:23:06.326619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ada63c51881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contest_id', sa.String(length=36), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_test_results',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('submission_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('test_case_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded', 'runtime_error', 'compilation_error', 'judge_error'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_used_kb', sa.Integer(), nullable=False),
    sa.Column('output_diff', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('identifier', table_name='languages')
    op.drop_table('languages')
    op.alter_column('contest_participants', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contest_participants', 'contest_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contest_participants', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contest_participants', 'joined_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('contest_id', table_name='contest_participants')
    op.drop_index('idx_contest_participants_contest_id', table_name='contest_participants')
    op.drop_index('idx_contest_participants_user_id', table_name='contest_participants')
    op.alter_column('contest_problems', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contest_problems', 'contest_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contest_problems', 'problem_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index('contest_id', table_name='contest_problems')
    op.drop_index('idx_contest_problems_contest_id', table_name='contest_problems')
    op.drop_index('idx_contest_problems_problem_id', table_name='contest_problems')
    op.alter_column('contests', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('contests', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('contests', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('problems', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('problems', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('problems', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index('idx_problems_created_by', table_name='problems')
    op.drop_index('idx_problems_difficulty', table_name='problems')
    op.alter_column('submissions', 'status',
               existing_type=mysql.ENUM('pending', 'accepted', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded', 'runtime_error', 'compilation_error'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('submissions', 'submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('idx_submissions_contest_id', table_name='submissions')
    op.drop_index('idx_submissions_problem_id', table_name='submissions')
    op.drop_index('idx_submissions_status', table_name='submissions')
    op.drop_index('idx_submissions_user_id', table_name='submissions')
    op.drop_constraint('submissions_ibfk_1', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_ibfk_3', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'contests', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_test_cases_problem_id', table_name='test_cases')
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_test_cases_problem_id', 'test_cases', ['problem_id'], unique=False)
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_ibfk_3', 'submissions', 'contests', ['contest_id'], ['id'])
    op.create_foreign_key('submissions_ibfk_1', 'submissions', 'users', ['user_id'], ['id'])
    op.create_index('idx_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_index('idx_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('idx_submissions_problem_id', 'submissions', ['problem_id'], unique=False)
    op.create_index('idx_submissions_contest_id', 'submissions', ['contest_id'], unique=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('submissions', 'status',
               existing_type=mysql.ENUM('pending', 'accepted', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded', 'runtime_error', 'compilation_error'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.create_index('idx_problems_difficulty', 'problems', ['difficulty'], unique=False)
    op.create_index('idx_problems_created_by', 'problems', ['created_by'], unique=False)
    op.alter_column('problems', 'created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('problems', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('problems', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('contests', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('contests', 'created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('contests', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_contest_problems_problem_id', 'contest_problems', ['problem_id'], unique=False)
    op.create_index('idx_contest_problems_contest_id', 'contest_problems', ['contest_id'], unique=False)
    op.create_index('contest_id', 'contest_problems', ['contest_id', 'problem_id'], unique=True)
    op.alter_column('contest_problems', 'problem_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('contest_problems', 'contest_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('contest_problems', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_contest_participants_user_id', 'contest_participants', ['user_id'], unique=False)
    op.create_index('idx_contest_participants_contest_id', 'contest_participants', ['contest_id'], unique=False)
    op.create_index('contest_id', 'contest_participants', ['contest_id', 'user_id'], unique=True)
    op.alter_column('contest_participants', 'joined_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('contest_participants', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('contest_participants', 'contest_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('contest_participants', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_table('languages',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('identifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('compile_command', mysql.TEXT(), nullable=True),
    sa.Column('run_command', mysql.TEXT(), nullable=False),
    sa.Column('file_extension', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('time_limit_multiplier', mysql.FLOAT(), server_default=sa.text('1'), nullable=True),
    sa.Column('memory_limit_multiplier', mysql.FLOAT(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('identifier', 'languages', ['identifier'], unique=True)
    op.drop_table('submission_test_results')
    op.drop_table('registration_requests')
    # ### end Alembic commands ###
